// Testes de tela: abre o app num Chrome ou Edge escondido e percorre as telas como uma pessoa faria.
// Roda em "npm test" e no GitHub antes de compilar o Android. Sem navegador no computador, avisa e passa.
// Uso: node scripts/e2e.mjs [--verbose]
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { launch, serve, sleep } from './headless.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..'), verbose = process.argv.includes('--verbose');
const browser = await launch({ width: 390, height: 780 });
if (!browser) { console.log('Testes de tela: Chrome ou Edge não encontrado neste computador, pulando.'); process.exit(0); }
const srv = await serve(root);
const results = [];
let failed = 0;

// Cada teste avalia código na página e precisa devolver um valor "verdadeiro"; um erro ou um valor falso reprova.
async function test(name, expression) {
  try {
    const v = await browser.eval(`(async()=>{${expression}})()`);
    if (v === false || v == null) throw new Error('devolveu ' + String(v));
    results.push({ name, ok: true, v }); if (verbose) console.log('ok  ' + name + (v === true ? '' : ': ' + JSON.stringify(v)));
  } catch (e) { failed++; results.push({ name, ok: false, e: e.message }); console.error('ERRO ' + name + ': ' + e.message); }
}
// Ajudas que ficam na página: clique por seletor (funciona em SVG também), espera, e leitura do estado salvo.
const HELPERS = `window.__t={click:s=>{const e=document.querySelector(s);if(!e)throw new Error('sem '+s+' (tela: '+((document.querySelector('#view h1')||{}).textContent||'?')+')');e.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));return e;},
 wait:ms=>new Promise(r=>setTimeout(r,ms)),S:()=>JSON.parse(localStorage.getItem('violao-diario-v1')||'null'),
 view:()=>(document.querySelector('#tabs [aria-current]')||{dataset:{}}).dataset.v,text:()=>document.querySelector('#view').innerText,
 broken:()=>/Algo deu errado nesta tela/.test(document.querySelector('#view').innerText),errs:()=>JSON.parse(localStorage.getItem('violao-diario-v1-erros')||'[]'),
 perfil:()=>{document.querySelector('[data-act="nav"][data-v="perfil"]').dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));}};`; // perfil(): abre a aba Perfil

try {
  await browser.goto(srv.url);
  await browser.eval(`localStorage.clear();localStorage.removeItem('violao-diario-v1-erros');'ok'`);
  await browser.goto(srv.url);
  await browser.eval(HELPERS);
  await browser.eval(`document.fonts.ready.then(()=>new Promise(r=>setTimeout(r,300)))`);

  await test('primeira tela: escolher nível e tempo e montar o treino', `const t=__t;t.click('[data-act="ob-level"][data-v="2"]');t.click('[data-act="ob-goal"][data-v="15"]');t.click('[data-act="ob-go"]');await t.wait(200);const S=t.S();return S.onboarded&&S.level===2&&S.goal===15&&document.querySelectorAll('.blk').length===4;`);
  await test('Hoje: blocos, revisão, roteiro e diário sem erro', `const t=__t;return !t.broken()&&/Treino de 15 minutos/.test(t.text())&&/Roteiro: nível 2/.test(t.text());`);
  await test('boas-vindas: aparecem depois do cadastro, o guia abre em Teoria, e somem ao fechar', `const t=__t;if(!document.querySelector('[data-act="welcome-done"]'))throw new Error('sem boas-vindas');t.click('[data-act="open-guia"]');await t.wait(150);const guia=document.querySelector('#guia'),open=guia&&guia.querySelector('details').open;t.click('[data-act="nav"][data-v="hoje"]');return !!guia&&open&&!document.querySelector('[data-act="welcome-done"]')&&t.S().welcomed===true;`);
  await test('meta semanal: 5 dias por semana aparece em Hoje', `const t=__t;t.perfil();t.click('[data-act="wgoal"][data-v="5"]');t.click('[data-act="nav"][data-v="hoje"]');const ok=/Esta semana: \\d de 5 dias/.test(t.text());t.perfil();t.click('[data-act="wgoal"][data-v="0"]');t.click('[data-act="nav"][data-v="hoje"]');return ok&&!/Esta semana:/.test(t.text());`);
  await test('bloco de treino: iniciar, concluir e desfazer', `const t=__t;t.click('[data-act="blk-start"]');await t.wait(100);t.click('[data-act="blk-done"]');await t.wait(200);const k=Object.keys(t.S().days).pop();const done=Object.keys(t.S().days[k].done).length===1;t.click('[data-act="blk-undo"]');await t.wait(100);return done&&Object.keys(t.S().days[k].done).length===0;`);
  await test('Hoje: “Outro exercício” troca a técnica do dia por outra da semana', `const t=__t;t.perfil();t.click('[data-act="goal"][data-v="20"]');t.click('[data-act="nav"][data-v="hoje"]');const txt=()=>{const b=[...document.querySelectorAll('.blk')].find(x=>/Técnica/.test(x.querySelector('h3').textContent));return b?b.querySelector('p').textContent:'';};const a=txt();if(!a||!document.querySelector('[data-act="blk-alt"]'))throw new Error('sem o bloco de técnica ou o botão');t.click('[data-act="blk-alt"]');const b=txt();const adj=!!t.S().adj&&t.S().adj.tech===b;t.perfil();t.click('[data-act="goal"][data-v="15"]');t.click('[data-act="nav"][data-v="hoje"]');if(b===a)throw new Error('a técnica não mudou');return adj;`);
  await test('todas as abas e subabas abrem sem erro', `const t=__t;const out=[];for(const [v,subs] of [['hoje',[]],['meu',[]],['treinar',['trocas','batidas','tempo','ouvido']],['ferramentas',['metronomo','afinador']],['acordes',['acordes','notas','teoria','descobrir']],['evolucao',['numeros','roteiro','musicas']]]){t.click('[data-act="nav"][data-v="'+v+'"]');if(t.broken()||!document.querySelector('#view').children.length)out.push(v);for(const s of subs){t.click('[data-act="sub"][data-v="'+s+'"]');if(t.broken())out.push(v+'/'+s);}}
    t.perfil();if(t.broken()||!/Seu nível/.test(t.text())||!document.querySelector('[data-act="pf-go"]'))out.push('perfil');t.click('[data-act="pf-go"][data-id="pf-ajuda"]');if(t.view()!=='perfil')out.push('perfil/aba');
    if(out.length)throw new Error('telas com erro: '+out.join(', '));return true;`);
  await test('níveis 7, 8 e 9: Hoje monta o treino em cada um', `const t=__t;const out=[];for(const n of [7,8,9]){t.perfil();t.click('[data-act="set-level"][data-l="'+n+'"]');t.click('[data-act="nav"][data-v="hoje"]');if(t.broken()||!new RegExp('Nível '+n+',').test(t.text())||document.querySelectorAll('.blk').length<4)out.push(n);}
    t.perfil();t.click('[data-act="set-level"][data-l="2"]');t.click('[data-act="nav"][data-v="hoje"]');if(out.length)throw new Error('níveis com erro: '+out.join(', '));return true;`);
  { // barra de baixo: os nomes das abas cabem na coluna em várias larguras de tela e crescem com ela
    const fits = [];
    for (const w of [320, 360, 412, 768]) {
      await browser.cdp.send('Emulation.setDeviceMetricsOverride', { width: w, height: 700, deviceScaleFactor: 1, mobile: true });
      await browser.eval('new Promise(r=>setTimeout(r,80))');
      fits.push(await browser.eval(`(()=>{const bad=[];document.querySelectorAll('#tabs button').forEach(b=>{const tn=[...b.childNodes].find(n=>n.nodeType===3&&n.textContent.trim());if(!tn)return;const rg=document.createRange();rg.selectNodeContents(tn);const w=rg.getBoundingClientRect().width;if(w>b.clientWidth-1)bad.push(tn.textContent.trim()+' '+Math.round(w)+'px na coluna de '+b.clientWidth+'px');});return {w:${w},bad,px:parseFloat(getComputedStyle(document.querySelector('#tabs button')).fontSize)};})()`));
    }
    await browser.cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 640, deviceScaleFactor: 1, mobile: true });
    await test('barra de baixo: os nomes das abas cabem em 320, 360, 412 e 768 px e crescem com a tela', `const r=${JSON.stringify(fits)};const bad=r.filter(x=>x.bad.length);if(bad.length)throw new Error(bad.map(x=>x.w+'px: '+x.bad.join(', ')).join('; '));return r[0].px>=9&&r[1].px>r[0].px&&r[2].px>r[1].px&&r[3].px>r[2].px;`);
  }
  await test('depois do nível 9: Hoje vira manutenção, com quatro blocos e o motivo de cada um', `const t=__t;t.perfil();t.click('[data-act="set-level"][data-l="9"]');t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="roteiro"]');const ks=[...document.querySelectorAll('[data-act="skill"]')].map(b=>b.dataset.k).filter(k=>k.startsWith('9.'));if(ks.length!==4)throw new Error('metas do nível 9: '+ks.length);ks.forEach(k=>t.click('[data-act="skill"][data-k="'+k+'"]'));
    t.click('[data-act="nav"][data-v="hoje"]');const txt=t.text(),blocos=document.querySelectorAll('.blk').length,why=[...document.querySelectorAll('.why p')].map(p=>p.textContent);
    t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="roteiro"]');ks.forEach(k=>t.click('[data-act="skill"][data-k="'+k+'"]'));t.perfil();t.click('[data-act="set-level"][data-l="2"]');t.click('[data-act="nav"][data-v="hoje"]');
    if(!/Manutenção: roteiro concluído/.test(txt))throw new Error('sem o cabeçalho de manutenção');if(blocos<4)throw new Error('blocos: '+blocos);if(!why.some(w=>/Manutenção/.test(w)))throw new Error('sem os motivos de manutenção');return Object.keys(t.S().skills).length===0&&t.S().level===2;`);
  await test('Hoje: a linha "Mais" abre o diário e lembra que ficou aberta', `const t=__t;const d=document.querySelector('#hoje-more');if(!d||d.open)throw new Error('linha Mais ausente ou aberta');d.open=true;d.dispatchEvent(new Event('toggle'));await t.wait(50);const saved=t.S().hojeMore===true&&!!document.querySelector('#d-note');d.open=false;d.dispatchEvent(new Event('toggle'));await t.wait(50);return saved&&t.S().hojeMore===false;`);
  await test('ouvido: as seis modalidades geram pergunta', `const t=__t;t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="ouvido"]');const n=[];for(const s of ['mm','qual','ivl','prog']){t.click('[data-act="sub"][data-g="ouvido"][data-v="'+s+'"]');n.push(document.querySelectorAll('.opt').length);}t.click('[data-act="sub"][data-g="ouvido"][data-v="sing"]');const sing=/Cante a nota/.test(t.text());t.click('[data-act="sub"][data-g="ouvido"][data-v="fb"]');const fb=document.querySelectorAll('.fb button[data-act="ear-fb"]').length;if(fb!==78)throw new Error('braço com '+fb+' casas');if(!(n[0]===2&&n[1]===2&&n[2]===3&&n[3]===4&&sing))throw new Error('opções por modalidade no nível 1: '+n.join(',')+' (cantar '+sing+')');return true;`);
  await test('ouvido, Braço: responder no braço conta e mostra as posições certas', `const t=__t;t.click('[data-act="ear-play"]');const before=(t.S().earLog.fb||{total:0}).total;t.click('[data-act="ear-fb"][data-si="0"][data-f="0"]');const after=(t.S().earLog.fb||{total:0}).total;const marked=document.querySelectorAll('.fb button.right').length,texto=/Certo|Era /.test(t.text());t.click('[data-act="ear-next"]');const nova=!document.querySelector('.fb button.right')&&!document.querySelector('.fb button.wrong');if(after!==before+1||marked<1||!texto||!nova)throw new Error('total '+before+' para '+after+', marcadas '+marked+', texto '+texto+', nova '+nova);return true;`);
  await test('metrônomo: liga, muda BPM e desliga', `const t=__t;t.click('[data-act="nav"][data-v="ferramentas"]');t.click('[data-act="sub"][data-g="ferramentas"][data-v="metronomo"]');t.click('#m-go');await t.wait(300);const on=document.querySelector('#m-go').textContent==='Parar';t.click('[data-act="m-bpm"][data-d="5"]');const bpm=+document.querySelector('#m-num').textContent;t.click('#m-go');return on&&bpm===75&&document.querySelector('#m-go').textContent==='Iniciar';`);
  await test('metrônomo: som de madeira usa ruído e o piscar liga', `const t=__t;t.click('[data-act="nav"][data-v="ferramentas"]');t.click('[data-act="sub"][data-g="ferramentas"][data-v="metronomo"]');const P=(window.AudioContext||window.webkitAudioContext).prototype,os=P.createBufferSource;let n=0;P.createBufferSource=function(){n++;return os.call(this);};
    t.click('[data-act="m-click"][data-v="madeira"]');t.click('[data-act="m-flash"]');t.click('#m-go');await t.wait(700);const flashed=document.body.classList.contains('flash')||n>0;t.click('#m-go');P.createBufferSource=os;const S=t.S();t.click('[data-act="m-click"][data-v="beep"]');t.click('[data-act="m-flash"]');if(!(n>0&&S.mclick==='madeira'&&S.mflash===true))throw new Error('ruídos '+n+', '+JSON.stringify([S.mclick,S.mflash]));return n;`);
  await test('metrônomo: a bateria toca bumbo, caixa e chimbal', `const t=__t;t.click('[data-act="nav"][data-v="ferramentas"]');t.click('[data-act="sub"][data-g="ferramentas"][data-v="metronomo"]');const P=(window.AudioContext||window.webkitAudioContext).prototype,os=P.createBufferSource,oo=P.createOscillator;let n=0,o=0;P.createBufferSource=function(){n++;return os.call(this);};P.createOscillator=function(){o++;return oo.call(this);};
    try{t.click('[data-act="m-click"][data-v="bateria"]');t.click('#m-go');await t.wait(2000);t.click('#m-go');if(t.S().mclick!=='bateria')throw new Error('não guardou o som');if(n<3||o<1)throw new Error('ruídos '+n+', osciladores '+o);return true;}finally{P.createBufferSource=os;P.createOscillator=oo;t.click('[data-act="m-click"][data-v="beep"]');}`);
  await test('batidas: todas as batidas tocam junto por um compasso', `const t=__t;t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="batidas"]');const ids=[...document.querySelectorAll('[data-act="gr-pat"]')].map(b=>b.dataset.v);for(const id of ids){t.click('[data-act="gr-pat"][data-v="'+id+'"]');for(let i=0;i<20;i++)t.click('[data-act="gr-bpm"][data-d="4"]');t.click('[data-act="gr-toggle"]');await t.wait(2600);if(document.querySelector('[data-act="gr-toggle"]').textContent!=='Parar')throw new Error('não tocou: '+id);t.click('[data-act="gr-toggle"]');}return ids.length;`);
  await test('descobrir: um C marcado no diagrama ganha nome, um G/B também, e a forma de E na 3ª casa é G', `const t=__t;t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="descobrir"]');const nm=()=>document.querySelector('#cf-name').textContent.trim();
    t.click('[data-act="cf-cell"][data-si="1"][data-f="3"]');t.click('[data-act="cf-cell"][data-si="2"][data-f="2"]');t.click('[data-act="cf-str"][data-si="3"]');t.click('[data-act="cf-cell"][data-si="4"][data-f="1"]');t.click('[data-act="cf-str"][data-si="5"]');
    const c=nm(),lib=/É o C da biblioteca/.test(t.text());t.click('[data-act="cf-play"]');
    t.click('[data-act="cf-clear"]');t.click('[data-act="cf-cell"][data-si="1"][data-f="2"]');t.click('[data-act="cf-str"][data-si="2"]');t.click('[data-act="cf-str"][data-si="3"]');t.click('[data-act="cf-str"][data-si="4"]');t.click('[data-act="cf-cell"][data-si="5"][data-f="3"]');const gb=nm();
    const f1=document.querySelector('#ms-name').textContent.trim(),libF=/É o F da biblioteca/.test(t.text());t.click('[data-act="ms-fret"][data-d="1"]');t.click('[data-act="ms-fret"][data-d="1"]');const g=document.querySelector('#ms-name').textContent.trim();t.click('[data-act="ms-form"][data-v="4"]');const cm=document.querySelector('#ms-name').textContent.trim();t.click('[data-act="ms-play"]');
    t.click('[data-act="cf-clear"]');if(c!=='C'||!lib||gb!=='G/B'||f1!=='F'||!libF||g!=='G'||cm!=='Cm')throw new Error([c,lib,gb,f1,libF,g,cm].join(' | '));return true;`);
  await test('acordes meus: guardar do Descobrir, aparecer na biblioteca e na cifra, e remover', `const t=__t;t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="descobrir"]');t.click('[data-act="cf-clear"]');
    t.click('[data-act="cf-cell"][data-si="1"][data-f="3"]');t.click('[data-act="cf-cell"][data-si="2"][data-f="2"]');t.click('[data-act="cf-cell"][data-si="3"][data-f="2"]');t.click('[data-act="cf-cell"][data-si="4"][data-f="1"]');t.click('[data-act="cf-str"][data-si="5"]');
    const nome=document.querySelector('#cf-name').textContent.trim();if(nome!=='C6')throw new Error('nome: '+nome);if(!document.querySelector('#mc-name'))throw new Error('sem o campo para guardar');t.click('[data-act="mc-save"]');await t.wait(50);
    const mc=t.S().mychords;if(!mc||mc.length!==1||mc[0].n!=='C6')throw new Error('não guardou: '+JSON.stringify(mc));if(!/seu acorde C6/.test(t.text()))throw new Error('o identificador não reconheceu o acorde meu');
    t.click('[data-act="sub"][data-g="acordes"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="meus"]');const tile=[...document.querySelectorAll('.ctile .name')].some(e=>/C6/.test(e.textContent));t.click('[data-act="sub"][data-g="filtro"][data-v="todos"]');
    t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');document.querySelector('#s-title').value='Com acorde meu';document.querySelector('#s-cifra').value='C6  G\\nletra';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Com acorde meu').id;t.click('[data-act="song-play"][data-id="'+id+'"]');const btn=!!document.querySelector('.cif-ch[data-c="C6"]:not(.off)');t.click('[data-act="song-close"]');t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="song-del"][data-id="'+id+'"]');
    t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="descobrir"]');t.click('[data-act="mc-del"][data-c="C6"]');await t.wait(50);const gone=t.S().mychords.length===0;t.click('[data-act="cf-clear"]');
    if(!tile||!btn||!gone)throw new Error('biblioteca '+tile+', cifra '+btn+', removido '+gone);return true;`);
  await test('biblioteca: o filtro “Das minhas músicas” mostra só os acordes das músicas cadastradas', `const t=__t;t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="musicas"]');const vazio=/Cadastre músicas/.test(t.text())&&!document.querySelector('.ctile');
    t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');document.querySelector('#s-title').value='Filtro';document.querySelector('#s-chords').value='G D Em C';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Filtro').id;
    t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="musicas"]');const nomes=[...document.querySelectorAll('.ctile .name')].map(e=>e.textContent.trim().split(' ')[0]).sort().join(',');t.click('[data-act="sub"][data-g="filtro"][data-v="todos"]');
    t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="song-del"][data-id="'+id+'"]');if(!vazio||nomes!=='C,D,Em,G')throw new Error('vazio '+vazio+', acordes: '+nomes);return true;`);
  await test('biblioteca: todos os acordes têm diagrama e teoria', `const t=__t;t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="todos"]');const names=[...document.querySelectorAll('.ctile .name')].map(n=>n.textContent.trim().replace(/ fácil$/,''));if(document.querySelectorAll('.ctile svg').length!==names.length)throw new Error('diagrama faltando');t.click('[data-act="sub"][data-g="acordes"][data-v="teoria"]');const bad=[];for(const n of names){const b=[...document.querySelectorAll('[data-act="th-pick"]')].find(x=>x.dataset.c===n);if(!b){bad.push(n);continue;}b.dispatchEvent(new MouseEvent('click',{bubbles:true}));if(t.broken()||document.querySelector('.thname').textContent!==n)bad.push(n);}if(bad.length)throw new Error('teoria falhou em '+bad.join(', '));return names.length;`);
  await test('escalas: tocar junto marca notas no braço', `const t=__t;t.click('[data-act="sg-toggle"]');await t.wait(1400);const on=!!document.querySelector('.sfb circle.on');t.click('[data-act="sg-toggle"]');return on;`);
  await test('músicas: adicionar, abrir a cifra, transpor e tocar junto', `const t=__t;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');document.querySelector('#s-title').value='Teste';document.querySelector('#s-chords').value='G D Em C';document.querySelector('#s-cifra').value='G   D   Em   C\\nletra da música';t.click('[data-act="song-add"]');t.click('[data-act="song-play"]');const n0=document.querySelectorAll('.cif-ch[data-i]').length;if(document.querySelectorAll('.cmini .chord').length!==4)throw new Error('faixa de acordes: '+document.querySelectorAll('.cmini .chord').length);t.click('[data-act="song-tr"][data-d="1"]');t.click('[data-act="song-tr"][data-d="1"]');const first=document.querySelector('.cif-ch').textContent;t.click('[data-act="song-playalong"]');await t.wait(300);const playing=document.querySelector('[data-act="song-playalong"]').textContent==='Parar';t.click('[data-act="song-playalong"]');
    t.click('[data-act="song-stage"]');const stage=document.body.classList.contains('stage')&&getComputedStyle(document.querySelector('.tabs')).display==='none'&&!!document.querySelector('.cifra');t.click('[data-act="song-stage"]');const unstaged=!document.body.classList.contains('stage');
    t.click('[data-act="song-close"]');if(!stage||!unstaged)throw new Error('modo palco: '+stage+' '+unstaged);return n0===4&&first==='A'&&playing;`);
  await test('sua batida: montar, salvar, tocar junto, aparecer nas músicas e em Meu treino, remover', `const t=__t;t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="batidas"]');t.click('[data-act="mp-n"][data-v="6"]');t.click('[data-act="mp-n"][data-v="8"]');
    [0,2,4,6].forEach(i=>t.click('[data-act="mp-cell"][data-i="'+i+'"]'));t.click('[data-act="mp-cell"][data-i="3"]');t.click('[data-act="mp-cell"][data-i="3"]');
    document.querySelector('#mp-name').value='Minha levada';t.click('[data-act="mp-save"]');await t.wait(100);const p=t.S().mypats[0];if(!p||p.name!=='Minha levada'||p.cells.join()!=='↓,,↓,↑,↓,,↓,')throw new Error('não salvou: '+JSON.stringify(t.S().mypats));
    const chip=document.querySelector('[data-act="gr-pat"][data-v="'+p.id+'"]');if(!chip||chip.getAttribute('aria-pressed')!=='true')throw new Error('a batida nova não ficou escolhida');
    for(let i=0;i<20;i++)t.click('[data-act="gr-bpm"][data-d="4"]');t.click('[data-act="gr-toggle"]');await t.wait(1500);const tocou=document.querySelector('[data-act="gr-toggle"]').textContent==='Parar';t.click('[data-act="gr-toggle"]');
    t.click('[data-act="nav"][data-v="meu"]');let abriu=false;if(!document.querySelector('[data-act="ce-pat"]')){t.click('[data-act="ce-new"]');abriu=true;}const emMeu=!!document.querySelector('[data-act="ce-pat"][data-v="'+p.id+'"]');if(abriu)t.click('[data-act="ce-cancel"]');
    t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');const sel=document.querySelector('#sv-pat'),naMusica=!!(sel&&sel.querySelector('option[value="'+p.id+'"]'));t.click('[data-act="song-close"]');
    t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="batidas"]');t.click('[data-act="mp-del"][data-id="'+p.id+'"]');await t.wait(50);const sumiu=t.S().mypats.length===0&&!document.querySelector('[data-act="gr-pat"][data-v="'+p.id+'"]');
    if(!tocou||!emMeu||!naMusica||!sumiu)throw new Error('tocou '+tocou+', Meu treino '+emMeu+', música '+naMusica+', removida '+sumiu);return true;`);
  await test('atalhos de teclado: número troca de aba, espaço liga o metrônomo, setas mudam o BPM, Esc sai do palco', `const t=__t,key=(k,el)=>(el||document.body).dispatchEvent(new KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true}));key('4');if(t.view()!=='ferramentas')throw new Error('aba: '+t.view());t.click('[data-act="sub"][data-g="ferramentas"][data-v="metronomo"]');const b0=+document.querySelector('#m-num').textContent;key('ArrowUp');key('ArrowUp');key('ArrowDown');const b1=+document.querySelector('#m-num').textContent;key(' ');await t.wait(200);const on=document.querySelector('#m-go').textContent;key(' ');await t.wait(100);const off=document.querySelector('#m-go').textContent;
    const inp=document.createElement('input');document.body.appendChild(inp);key('1',inp);const ficou=t.view()==='ferramentas';inp.remove();
    key('6');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-stage"]');const palco=document.body.classList.contains('stage');key('Escape');const saiu=!document.body.classList.contains('stage');t.click('[data-act="song-close"]');key('1');
    if(b1!==b0+1)throw new Error('BPM '+b0+' -> '+b1);if(on===off)throw new Error('espaço: '+on+' / '+off);if(!ficou)throw new Error('atalho disparou dentro de um campo');if(!palco||!saiu)throw new Error('palco '+palco+', saiu '+saiu);return t.view()==='hoje';`);
  // cifra compartilhada com o site instalado (share_target): abre Adicionar música preenchido
  await browser.goto(srv.url + '?titulo=' + encodeURIComponent('Canção recebida') + '&texto=' + encodeURIComponent('Intro: C  G  Am  F\n\nC        G\nprimeira linha da letra\nAm       F\nsegunda linha'));
  await browser.eval(HELPERS);
  await test('cifra recebida de outro app: abre Adicionar música com nome e acordes preenchidos', `const t=__t;await t.wait(300);if(t.view()!=='evolucao')throw new Error('tela: '+t.view());const ti=document.querySelector('#s-title'),ch=document.querySelector('#s-chords'),cf=document.querySelector('#s-cifra');if(!ti||ti.value!=='Canção recebida')throw new Error('título: '+(ti&&ti.value));if(ch.value!=='C G Am F')throw new Error('acordes: '+ch.value);if(!/primeira linha/.test(cf.value))throw new Error('cifra vazia');t.click('[data-act="song-add"]');await t.wait(100);const s=t.S().songs.find(x=>x.title==='Canção recebida');if(!s||s.chords!=='C G Am F')throw new Error('música não salva');return location.search===''&&!t.broken();`);
  await test('música: Compartilhar manda nome, acordes e cifra como texto', `const t=__t;navigator.share=d=>{window.__shared=d;return Promise.resolve();};const id=t.S().songs.find(x=>x.title==='Canção recebida').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-share"][data-id="'+id+'"]');await t.wait(50);const d=window.__shared;delete navigator.share;if(!d)throw new Error('compartilhar não foi chamado');t.click('[data-act="song-close"]');return d.title==='Canção recebida'&&/Acordes: C G Am F/.test(d.text)&&/primeira linha/.test(d.text);`);
  await test('palco: tocar na cifra pausa e retoma a rolagem', `const t=__t;const id=t.S().songs.find(x=>x.title==='Canção recebida').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-stage"]');t.click('[data-act="song-speed"][data-v="2"]');const pre=document.querySelector('pre.cifra[data-act="song-tap"]');if(!pre)throw new Error('sem a cifra tocável');pre.dispatchEvent(new MouseEvent('click',{bubbles:true}));const paused=document.querySelector('[data-act="song-speed"][data-v="0"]').getAttribute('aria-pressed')==='true';pre.dispatchEvent(new MouseEvent('click',{bubbles:true}));const back=document.querySelector('[data-act="song-speed"][data-v="2"]').getAttribute('aria-pressed')==='true';t.click('[data-act="song-stage"]');t.click('[data-act="song-close"]');if(!paused||!back)throw new Error('pausa '+paused+', retomada '+back);return true;`);
  await test('cifra: tom provável (Sol maior para G D Em C; Dó maior para C G Am F)', `const t=__t;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');const id1=t.S().songs.find(x=>x.title==='Teste').id,id2=t.S().songs.find(x=>x.title==='Canção recebida').id;t.click('[data-act="song-play"][data-id="'+id1+'"]');t.click('[data-act="song-tr"][data-d="-1"]');t.click('[data-act="song-tr"][data-d="-1"]');const a=t.text();t.click('[data-act="song-close"]');t.click('[data-act="song-play"][data-id="'+id2+'"]');const b=t.text();t.click('[data-act="song-close"]');if(!/Tom provável: Sol maior \\(ou Mi menor\\)/.test(a))throw new Error('Teste: '+(a.match(/Tom provável[^.]*/)||['sem tom'])[0]);if(!/Tom provável: Dó maior/.test(b))throw new Error('Canção: '+(b.match(/Tom provável[^.]*/)||['sem tom'])[0]);return true;`);
  await test('remover música: pede confirmação e dá para desfazer', `const t=__t;document.querySelector('#s-title').value='Descartável';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Descartável').id,n=t.S().songs.length;t.click('[data-act="song-del"][data-id="'+id+'"]');const armed=t.S().songs.length===n&&/Confirmar remoção/.test(t.text());t.click('[data-act="song-del"][data-id="'+id+'"]');const gone=t.S().songs.length===n-1&&!!document.querySelector('[data-act="song-undo"]');t.click('[data-act="song-undo"]');const back=t.S().songs.length===n&&!!t.S().songs.find(x=>x.title==='Descartável');t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="nav"][data-v="hoje"]');t.click('[data-act="nav"][data-v="evolucao"]');const cleared=!document.querySelector('[data-act="song-undo"]');if(!armed||!gone||!back||!cleared)throw new Error('confirmação '+armed+', removida '+gone+', desfeita '+back+', limpa '+cleared);return t.S().songs.length===n-1;`);
  await test('cifra: seções viram atalhos, aparecem no trecho em loop, e o limite é de 12 mil caracteres', `const t=__t;document.querySelector('#s-title').value='Com seções';document.querySelector('#s-cifra').value='[Intro] G  C\\nRefrão:\\nD        Em\\nletra do refrão\\nPonte\\nC   G';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Com seções').id;t.click('[data-act="song-play"][data-id="'+id+'"]');
    const chips=[...document.querySelectorAll('[data-act="song-sec"]')].map(b=>b.textContent);const secs=document.querySelectorAll('.cif-sec').length;t.click('[data-act="song-sec"][data-n="1"]');const opt=[...document.querySelectorAll('#sv-lb option')].map(o=>o.textContent);
    const max=document.querySelector('#sv-cifra')?+document.querySelector('#sv-cifra').getAttribute('maxlength'):null;t.click('[data-act="song-edit"]');const max2=+document.querySelector('#sv-cifra').getAttribute('maxlength');t.click('[data-act="song-edit"]');t.click('[data-act="song-close"]');
    if(chips.join('|')!=='Intro|Refrão|Ponte'||secs!==3)throw new Error('seções: '+chips.join('|')+' ('+secs+')');if(!opt.some(x=>/Refrão/.test(x))||!opt.some(x=>/Ponte/.test(x)))throw new Error('trecho sem seções: '+opt.join(' / '));if(max2!==12000)throw new Error('limite: '+max2);return true;`);
  await test('músicas: busca e ordem por nome, e a lista volta à ordem de cadastro', `const t=__t;document.querySelector('#s-title').value='Quarta';document.querySelector('#s-chords').value='Am E';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Quarta').id;const busca=document.querySelector('#s-busca');if(!busca)throw new Error('sem a busca com quatro músicas');
    busca.value='seç';busca.dispatchEvent(new Event('input',{bubbles:true}));const n1=document.querySelectorAll('[data-act="song-play"]').length,foco=document.activeElement&&document.activeElement.id==='s-busca';const b2=document.querySelector('#s-busca');b2.value='';b2.dispatchEvent(new Event('input',{bubbles:true}));
    t.click('[data-act="song-sort"][data-v="nome"]');const nomes=[...document.querySelectorAll('[data-act="song-play"]')].map(b=>b.closest('.song').querySelector('h3').textContent);const semSetas=!document.querySelector('[data-act="song-move"]');t.click('[data-act="song-sort"][data-v="cadastro"]');const comSetas=!!document.querySelector('[data-act="song-move"]');
    t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="song-del"][data-id="'+id+'"]');if(n1!==1||!foco||nomes.join('|')!==nomes.slice().sort((a,b)=>a.localeCompare(b,'pt-BR')).join('|')||!semSetas||!comSetas)throw new Error('busca '+n1+', foco '+foco+', ordem '+nomes.join('|')+', setas '+semSetas+'/'+comSetas);return true;`);
  await test('tocar junto: bater o andamento define o BPM da música pelo toque', `const t=__t;const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');for(let i=0;i<4;i++){t.click('[data-act="song-tempo-tap"][data-id="'+id+'"]');await t.wait(500);}const bpm=t.S().songs.find(x=>x.id===id).bpm,shown=+document.querySelector('#gr-bpm').textContent;t.click('[data-act="song-close"]');if(bpm<108||bpm>132||shown!==bpm)throw new Error('BPM '+bpm+' (tela '+shown+')');return true;`);
  await test('acordes que faltam: a cifra com um acorde desconhecido leva a Descobrir com o nome pronto', `const t=__t;document.querySelector('#s-title').value='Com Cm9';document.querySelector('#s-cifra').value='Cm9  G';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Com Cm9').id;t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="musicas"]');const b=document.querySelector('[data-act="mc-new"][data-c="Cm9"]');if(!b)throw new Error('não listou o Cm9');t.click('[data-act="mc-new"][data-c="Cm9"]');const aviso=/Cm9/.test(t.text())&&!!document.querySelector('[data-act="mc-want-clear"]');t.click('[data-act="mc-want-clear"]');t.click('[data-act="sub"][data-g="acordes"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="todos"]');t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="song-del"][data-id="'+id+'"]');if(!aviso)throw new Error('Descobrir sem o aviso do Cm9');return true;`);
  await test('evolução: o painel Repertório conta as músicas por situação', `const t=__t;t.click('[data-act="sub"][data-g="evolucao"][data-v="numeros"]');const txt=t.text();t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');if(!/Repertório/.test(txt)||!/Dominadas/.test(txt)||!/Aprendendo/.test(txt))throw new Error('sem o painel Repertório');return true;`);
  await test('compartilhar no tom da tela: a cifra transposta sai com os acordes novos e a nota do tom', `const t=__t;navigator.share=d=>{window.__shared=d;return Promise.resolve();};const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-tr"][data-d="1"]');t.click('[data-act="song-tr"][data-d="1"]');t.click('[data-act="song-share"][data-id="'+id+'"]');await t.wait(50);const d=window.__shared;delete navigator.share;t.click('[data-act="song-tr"][data-d="-1"]');t.click('[data-act="song-tr"][data-d="-1"]');t.click('[data-act="song-close"]');if(!d)throw new Error('compartilhar não foi chamado');if(!/Tom: um tom acima/.test(d.text)||!/Acordes: A E F#m D/.test(d.text)||!/A   E   F#m   D/.test(d.text))throw new Error(d.text.slice(0,120));return true;`);
  await test('tocar junto: trecho em loop marca os acordes e toca só aquela parte', `const t=__t;const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');const la=document.querySelector('#sv-la'),lb=document.querySelector('#sv-lb');if(!la||!lb)throw new Error('sem os seletores de trecho');la.value='1';la.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#sv-lb').value='2';document.querySelector('#sv-lb').dispatchEvent(new Event('change',{bubbles:true}));const sel=document.querySelectorAll('.cif-ch.sel').length;for(let i=0;i<24;i++)t.click('[data-act="song-bpm"][data-d="4"]');t.click('[data-act="song-playalong"]');await t.wait(2600);const now=document.querySelector('.cif-ch.now'),di=now?+now.dataset.i:-1;t.click('[data-act="song-playalong"]');t.click('[data-act="song-loop-all"]');const all=document.querySelectorAll('.cif-ch.sel').length;t.click('[data-act="song-close"]');if(sel!==2||!(di===1||di===2)||all!==0)throw new Error('marcados '+sel+', tocando '+di+', depois '+all);return true;`);
  await test('tocar junto: a música inteira conta como tocada e, com três vezes, o app sugere marcar como dominada', `const t=__t;const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-playalong"]');await t.wait(8600);t.click('[data-act="song-playalong"]');const plays=t.S().songs.find(x=>x.id===id).plays||0;const sugerido=!!document.querySelector('[data-act="song-status"]');t.click('[data-act="song-close"]');if(plays<1)throw new Error('não contou a passagem inteira: '+plays);if(sugerido)throw new Error('sugeriu cedo demais');return true;`);
  await browser.eval(`(()=>{const k='violao-diario-v1',o=JSON.parse(localStorage.getItem(k));o.songs.find(x=>x.title==='Teste').plays=3;localStorage.setItem(k,JSON.stringify(o));return 'ok';})()`);
  await browser.goto(srv.url); await browser.eval(HELPERS);
  await test('cifra: com três passagens inteiras, "Marcar como dominada" aparece e funciona', `const t=__t;await t.wait(300);t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');const b=document.querySelector('[data-act="song-status"][data-v="dominada"]');if(!b)throw new Error('sem a sugestão');t.click('[data-act="song-status"][data-v="dominada"]');const st=t.S().songs.find(x=>x.id===id).status;t.click('[data-act="song-close"]');const sel=document.querySelector('select[data-song="'+id+'"]');sel.value='aprendendo';sel.dispatchEvent(new Event('change',{bubbles:true}));if(st!=='dominada')throw new Error('situação: '+st);return t.S().songs.find(x=>x.id===id).status==='aprendendo';`);
  await test('Voltar e Esc: fecham o desenho do acorde, a música e voltam para Hoje, um passo por vez', `const t=__t,esc=()=>document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('.cif-ch[data-i="0"]');const pop=!!document.querySelector('#cifpop');esc();const popClosed=!document.querySelector('#cifpop')&&!!document.querySelector('[data-act="song-close"]');esc();const songClosed=!document.querySelector('[data-act="song-close"]')&&t.view()==='evolucao';esc();const home=t.view()==='hoje';if(!pop||!popClosed||!songClosed||!home)throw new Error('popup '+pop+', fechou '+popClosed+', música '+songClosed+', Hoje '+home);return true;`);
  await test('volumes: violão e clique guardam a porcentagem', `const t=__t;t.perfil();const set=(id,v)=>{const el=document.querySelector('#'+id);el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));return el.closest('label').textContent;};const g=set('vol-guitar',60),c=set('vol-click',120);const S=t.S();const ok=S.volGuitar===60&&S.volClick===120&&/60%/.test(g)&&/120%/.test(c);set('vol-guitar',100);set('vol-click',100);t.click('[data-act="nav"][data-v="hoje"]');if(!ok)throw new Error(JSON.stringify([S.volGuitar,S.volClick,g,c]));return t.S().volGuitar===100;`);
  await test('conquistas: batida própria e primeira música dominada ficaram registradas, entre 21', `const t=__t;const b=t.S().badges;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="numeros"]');const txt=t.text();t.click('[data-act="nav"][data-v="hoje"]');if(!b.minhabatida||!b.musica1)throw new Error('faltam: '+JSON.stringify(Object.keys(b)));if(!/ de 21/.test(txt))throw new Error('contagem de conquistas não mostra 21');return true;`);
  await test('modo roda: no palco, Próxima e Anterior trocam de música sem sair do palco', `const t=__t;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-stage"]');const t0=document.querySelector('#view h2').textContent;const prox=document.querySelector('[data-act="song-nav"][data-d="1"]');if(!prox)throw new Error('sem o botão Próxima');t.click('[data-act="song-nav"][data-d="1"]');const t1=document.querySelector('#view h2').textContent,stage=document.body.classList.contains('stage');document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true,cancelable:true}));const t2=document.querySelector('#view h2').textContent;t.click('[data-act="song-stage"]');t.click('[data-act="song-close"]');if(t0!=='Teste'||t1===t0||!stage||t2!=='Teste')throw new Error([t0,t1,stage,t2].join(' | '));return true;`);
  await test('tocar junto: subir aos poucos sobe 4 BPM a cada volta completa', `const t=__t;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');document.querySelector('#s-title').value='Uma';document.querySelector('#s-cifra').value='G';t.click('[data-act="song-add"]');const id=t.S().songs.find(x=>x.title==='Uma').id;t.click('[data-act="song-play"][data-id="'+id+'"]');t.click('[data-act="song-ramp"][data-id="'+id+'"]');const b0=+document.querySelector('#gr-bpm').textContent;for(let i=0;i<30;i++)t.click('[data-act="song-bpm"][data-d="4"]');for(let i=0;i<10;i++)t.click('[data-act="song-bpm"][data-d="-4"]');const b1=+document.querySelector('#gr-bpm').textContent;t.click('[data-act="song-playalong"]');await t.wait(6500);const b2=+document.querySelector('#gr-bpm').textContent;t.click('[data-act="song-playalong"]');const ramp=t.S().songs.find(x=>x.id===id).ramp;t.click('[data-act="song-close"]');t.click('[data-act="song-del"][data-id="'+id+'"]');t.click('[data-act="song-del"][data-id="'+id+'"]');if(!ramp||b1!==120||b2<124)throw new Error('ramp '+ramp+', BPM '+b0+' -> '+b1+' -> '+b2);return true;`);
  await test('lembrete no calendário: o arquivo .ics tem o horário e a repetição diária', `const t=__t;t.perfil();t.click('[data-act="remind"][data-v="19:00"]');const ou=URL.createObjectURL,oc=HTMLAnchorElement.prototype.click;URL.createObjectURL=b=>{window.__ics=b;return 'blob:x';};HTMLAnchorElement.prototype.click=function(){};try{t.click('[data-act="remind-ics"]');await t.wait(50);}finally{URL.createObjectURL=ou;HTMLAnchorElement.prototype.click=oc;}const txt=window.__ics?await window.__ics.text():'';t.click('[data-act="remind"][data-v=""]');t.click('[data-act="nav"][data-v="hoje"]');if(!/RRULE:FREQ=DAILY/.test(txt)||!/T190000/.test(txt)||!/BEGIN:VALARM/.test(txt))throw new Error('ics: '+txt.slice(0,160));return true;`);
  await browser.eval(`(()=>{const k='violao-diario-v1',o=JSON.parse(localStorage.getItem(k));o.earRun={ivl:{ok:8,total:9}};o.earLvl={ivl:1,qual:1};localStorage.setItem(k,JSON.stringify(o));return 'ok';})()`);
  await browser.goto(srv.url); await browser.eval(HELPERS);
  await test('ouvido em níveis: a décima resposta com 80% sobe os intervalos ao nível 2, com quatro opções', `const t=__t;await t.wait(300);t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="ouvido"]');t.click('[data-act="sub"][data-g="ouvido"][data-v="ivl"]');const n1=document.querySelectorAll('.opt').length,txt1=t.text();t.click('[data-act="ear-play"]');const first=document.querySelector('[data-act="ear-ans"]');t.click('[data-act="ear-ans"][data-v="'+first.dataset.v+'"]');const lvl=t.S().earLvl.ivl;t.click('[data-act="ear-next"]');const n2=document.querySelectorAll('.opt').length,txt2=t.text();t.click('[data-act="nav"][data-v="hoje"]');if(n1!==3||!/Nível do ouvido: 1 de 3/.test(txt1))throw new Error('nível 1: '+n1+' opções');if(lvl!==2||n2!==4||!/Nível do ouvido: 2 de 3/.test(txt2))throw new Error('depois: nível '+lvl+', '+n2+' opções');return true;`);
  await test('leitor de tela: ao trocar de aba, o foco vai para o título da tela', `const t=__t;t.click('[data-act="nav"][data-v="acordes"]');const a=document.activeElement,ok1=a&&/^H[12]$/.test(a.tagName)&&a.closest('#view');t.click('[data-act="nav"][data-v="hoje"]');const b=document.activeElement,ok2=b&&/^H[12]$/.test(b.tagName)&&b.closest('#view');if(!ok1||!ok2)throw new Error('foco em '+(a&&a.tagName)+' / '+(b&&b.tagName));return true;`);
  await test('meu treino: montar, salvar e compartilhar por código', `const t=__t;t.click('[data-act="nav"][data-v="meu"]');t.click('[data-act="ce-suggest"]');t.click('[data-act="ce-save"]');await t.wait(100);const n=t.S().custom.length;const code=__t.S().custom[0];document.querySelector('details.tcard summary').click();document.querySelector('#ct-code').value=location.origin+'/#treino='+btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify({n:'Recebido',c:code.chords,p:code.pats,b:code.bpm,m:code.min,r:0})))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'');t.click('[data-act="ct-import"]');await t.wait(100);return n===1&&t.S().custom.length===2&&t.S().custom[1].name==='Recebido';`);
  // cronômetro de prática livre: liga, e um começo guardado 5 minutos atrás soma 5 min ao parar
  await test('cronômetro de prática livre: liga e mostra o relógio', `const t=__t;t.click('[data-act="nav"][data-v="hoje"]');t.click('[data-act="free-start"]');await t.wait(50);if(!(t.S().freeStart>0))throw new Error('não ligou');if(!document.querySelector('#free-clock'))throw new Error('sem relógio');if(!document.querySelector('#hoje-more').open)throw new Error('a linha Mais não abriu');return true;`);
  await browser.eval(`(()=>{const k='violao-diario-v1',o=JSON.parse(localStorage.getItem(k));o.freeStart=Date.now()-5*60000;localStorage.setItem(k,JSON.stringify(o));return 'ok';})()`);
  await browser.goto(srv.url); await browser.eval(HELPERS);
  await test('cronômetro de prática livre: ao parar, soma os minutos ao dia', `const t=__t;await t.wait(300);const before=(t.S().days[Object.keys(t.S().days).sort().pop()]||{}).min||0;if(!/há 5 min/.test(t.text()))throw new Error('relógio não voltou com 5 min');t.click('[data-act="free-stop"]');await t.wait(100);const S=t.S(),after=(S.days[Object.keys(S.days).sort().pop()]||{}).min||0;if(S.freeStart!==0)throw new Error('não parou');if(after!==before+5)throw new Error('minutos: '+before+' -> '+after);return true;`);
  await test('evolução: gráficos de 12 semanas e minutos por semana', `const t=__t;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="numeros"]');const svg=document.querySelector('svg[aria-label^="Minutos por semana"]');if(!svg)throw new Error('sem o gráfico das semanas');const bars=svg.querySelectorAll('rect').length;if(bars!==12)throw new Error('barras: '+bars);return /Últimas 12 semanas/.test(t.text());`);
  await test('manifesto: as capturas da instalação existem', `const m=await (await fetch('manifest.webmanifest')).json();if(!m.screenshots||m.screenshots.length<4)throw new Error('sem capturas');const ok=await Promise.all(m.screenshots.map(s=>fetch(s.src).then(r=>r.ok)));const bad=m.screenshots.filter((s,i)=>!ok[i]).map(s=>s.src);if(bad.length)throw new Error('faltam: '+bad.join(', '));return m.share_target&&m.share_target.params.text==='texto';`);
  await test('treino compartilhado leva a batida própria: quem recebe ganha a batida', `const t=__t;t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="batidas"]');t.click('[data-act="mp-cell"][data-i="0"]');t.click('[data-act="mp-cell"][data-i="4"]');document.querySelector('#mp-name').value='Levada do link';t.click('[data-act="mp-save"]');const pid=t.S().mypats.find(p=>p.name==='Levada do link').id;
    t.click('[data-act="nav"][data-v="meu"]');if(!document.querySelector('[data-act="ce-pat"]'))t.click('[data-act="ce-new"]');t.click('[data-act="ce-suggest"]');t.click('[data-act="ce-pat"][data-v="'+pid+'"]');t.click('[data-act="ce-save"]');await t.wait(100);const tr=t.S().custom.find(x=>x.pats.includes(pid));if(!tr)throw new Error('o treino não guardou a batida própria');
    navigator.share=d=>{window.__url=d.url;return Promise.resolve();};t.click('[data-act="ct-share"][data-id="'+tr.id+'"]');await t.wait(50);delete navigator.share;const url=window.__url;if(!url||!/#treino=/.test(url))throw new Error('sem link: '+url);
    t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="batidas"]');t.click('[data-act="mp-del"][data-id="'+pid+'"]');if(t.S().mypats.some(p=>p.id===pid))throw new Error('não removeu a batida');
    t.click('[data-act="nav"][data-v="meu"]');const sum=document.querySelector('details.tcard summary');if(sum)sum.click();document.querySelector('#ct-code').value=url;t.click('[data-act="ct-import"]');await t.wait(100);const back=t.S().mypats.find(p=>p.id===pid),novo=t.S().custom.filter(x=>x.pats.includes(pid)).length;
    t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="batidas"]');t.click('[data-act="mp-del"][data-id="'+pid+'"]');t.click('[data-act="nav"][data-v="hoje"]');if(!back||back.name!=='Levada do link'||back.cells.join()!=='↓,,,,↓,,,'||novo<1)throw new Error('batida de volta: '+JSON.stringify(back)+', treinos com ela: '+novo);return true;`);
  { // imprimir a cifra: com a mídia de impressão emulada, os controles somem e a cifra fica
    await browser.eval(`(()=>{const t=__t;t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="musicas"]');const id=t.S().songs.find(x=>x.title==='Teste').id;t.click('[data-act="song-play"][data-id="'+id+'"]');return 'ok';})()`);
    await browser.cdp.send('Emulation.setEmulatedMedia', { media: 'print' });
    const printed = await browser.eval(`(()=>{const d=s=>{const e=document.querySelector(s);return e?getComputedStyle(e).display:'ausente';};return {play:d('.svplay'),tom:d('.svtom'),cifra:d('pre.cifra'),tabs:d('.tabs'),link:!!document.querySelector('[data-act="print"]')};})()`);
    await browser.cdp.send('Emulation.setEmulatedMedia', { media: '' });
    await browser.eval(`(()=>{__t.click('[data-act="song-close"]');return 'ok';})()`);
    await test('imprimir a cifra: os controles somem e a cifra fica', `const r=${JSON.stringify(printed)};if(!r.link)throw new Error('sem o link Imprimir');if(r.play!=='none'||r.tom!=='none'||r.tabs!=='none'||r.cifra==='none'||r.cifra==='ausente')throw new Error(JSON.stringify(r));return true;`);
  }
  await test('perfil: letra maior, tema escuro e canhoto', `const t=__t;t.perfil();t.click('[data-act="font"][data-v="2"]');t.click('[data-act="theme"][data-v="dark"]');t.click('[data-act="lefty"][data-v="1"]');const ok=getComputedStyle(document.documentElement).fontSize==='19px'&&document.documentElement.dataset.theme==='dark'&&t.S().lefty===true;t.click('[data-act="font"][data-v="0"]');t.click('[data-act="theme"][data-v=""]');t.click('[data-act="lefty"][data-v="0"]');return ok;`);
  await test('violão do app: nylon, aço e elétrico tocam (o aço com duas cordas por nota)', `const t=__t,P=(window.AudioContext||window.webkitAudioContext).prototype,os=P.createBufferSource;let n=0;P.createBufferSource=function(){n++;return os.call(this);};
    t.perfil();const counts={};
    for(const k of ['nylon','aco','eletrico']){t.click('[data-act="guitar"][data-v="'+k+'"]');n=0;t.click('[data-act="chord-play"][data-c="G"]');counts[k]=n;}
    P.createBufferSource=os;t.click('[data-act="guitar"][data-v="nylon"]');if(!(counts.nylon===6&&counts.aco===12&&counts.eletrico===6&&t.S().guitar==='nylon'))throw new Error(JSON.stringify(counts));return true;`);
  await test('notas gravadas: os arquivos existem, decodificam e o app as usa', `const t=__t;const ab=await fetch('sons/nylon/52.mp3').then(r=>{if(!r.ok)throw new Error('http '+r.status);return r.arrayBuffer();});
    const buf=await new Promise((res,rej)=>{const p=new OfflineAudioContext(1,1,44100).decodeAudioData(ab,res,rej);if(p&&p.then)p.then(res,rej);});if(!(buf.duration>.5))throw new Error('duração '+buf.duration);
    t.perfil();t.click('[data-act="guitar"][data-v="nylon"]');
    let txt='';for(let i=0;i<40;i++){txt=document.querySelector('#smp-state').textContent;if(/prontas/.test(txt))break;await t.wait(250);}if(!/prontas/.test(txt))throw new Error('estado: '+txt);
    const P=(window.AudioContext||window.webkitAudioContext).prototype,ob=P.createBiquadFilter;let filt=0;P.createBiquadFilter=function(){filt++;return ob.call(this);};t.click('[data-act="play-notes"][data-m="40,45,50,55,59,64"]');P.createBiquadFilter=ob;
    return 'duração '+buf.duration.toFixed(2)+' s, notas suaves com filtro: '+filt;`);
  await test('cópias automáticas: a de hoje existe e restaurar volta o nível', `const t=__t;let list=[];for(let i=0;i<30;i++){t.perfil();list=[...document.querySelectorAll('[data-act="bak-restore"]')];if(list.length)break;await t.wait(300);t.click('[data-act="nav"][data-v="hoje"]');}
    if(list.length!==1)throw new Error('cópias: '+list.length);const before=t.S().level;t.click('[data-act="set-level"][data-l="3"]');if(t.S().level!==3)throw new Error('nível não mudou');
    t.click('[data-act="bak-restore"]');t.click('[data-act="bak-restore"]');await t.wait(400);if(t.S().level!==before)throw new Error('restaurou nível '+t.S().level);return true;`);
  await test('cópia ao sair: ir para segundo plano grava uma cópia que aparece no alto da lista', `const t=__t;Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));await t.wait(500);t.perfil();await t.wait(300);t.perfil();const first=document.querySelector('[data-act="bak-restore"]');const li=first&&first.closest('li');if(!li||!/Ao sair/.test(li.textContent))throw new Error('sem a cópia ao sair: '+(li?li.textContent:'nenhuma'));t.click('[data-act="nav"][data-v="hoje"]');return true;`);
  await test('cartão de progresso: gera uma imagem PNG', `const t=__t;t.click('[data-act="nav"][data-v="hoje"]');t.click('[data-act="free-add"][data-v="5"]');t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="numeros"]');let blob=null;const oc=URL.createObjectURL,ok=HTMLAnchorElement.prototype.click,sh=navigator.share;
    try{URL.createObjectURL=b=>{blob=b;return 'blob:x';};HTMLAnchorElement.prototype.click=function(){if(!this.download)ok.call(this);};navigator.share=undefined;t.click('[data-act="share-card"]');for(let i=0;i<20&&!blob;i++)await t.wait(150);}
    finally{URL.createObjectURL=oc;HTMLAnchorElement.prototype.click=ok;navigator.share=sh;}
    if(!blob||blob.type!=='image/png'||blob.size<5000)throw new Error('imagem: '+(blob&&blob.type)+' '+(blob&&blob.size));return Math.round(blob.size/1024)+' KB';`);
  await test('exportar e importar o progresso', `const t=__t;let blob=null;const oc=URL.createObjectURL;URL.createObjectURL=b=>{blob=b;return 'blob:x';};const ok=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(!this.download)ok.call(this);};t.perfil();t.click('[data-act="export"]');URL.createObjectURL=oc;HTMLAnchorElement.prototype.click=ok;const txt=await blob.text();const before=t.S().level;t.click('[data-act="set-level"][data-l="3"]');document.querySelector('details.tcard summary').click();document.querySelector('#imp-text').value=txt;t.click('[data-act="imp-paste"]');t.click('[data-act="imp-go"]');await t.wait(100);return JSON.parse(txt).app==='violao-diario'&&t.S().level===before;`);
  // criar um perfil recarrega a página: o clique é agendado e o teste seguinte espera a página voltar
  const reloaded = browser.cdp.wait('Page.loadEventFired');
  await test('importar juntando: um arquivo com outro dia e outra música soma ao aparelho sem apagar nada', `const t=__t;let blob=null;const oc=URL.createObjectURL;URL.createObjectURL=b=>{blob=b;return 'blob:x';};const ok=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(!this.download)ok.call(this);};t.perfil();t.click('[data-act="export"]');URL.createObjectURL=oc;HTMLAnchorElement.prototype.click=ok;const o=JSON.parse(await blob.text());
    o.data.days['2020-01-01']={min:7,done:{}};o.data.songs=[{id:'sx1',title:'Vinda de outro aparelho',chords:'A D',cifra:'',status:'devagar'}];o.data.level=1;const antes=t.S(),nSongs=antes.songs.length;
    document.querySelector('details.tcard summary').click();document.querySelector('#imp-text').value=JSON.stringify(o);t.click('[data-act="imp-paste"]');t.click('[data-act="imp-merge"]');await t.wait(100);const S=t.S();
    if(!S.days['2020-01-01']||S.days['2020-01-01'].min!==7)throw new Error('o dia não entrou');if(S.songs.length!==nSongs+1||!S.songs.some(s=>s.title==='Vinda de outro aparelho'))throw new Error('músicas: '+S.songs.length+' (antes '+nSongs+')');if(S.level!==antes.level)throw new Error('o nível mudou para '+S.level);
    t.click('[data-act="imp-undo"]');await t.wait(100);t.click('[data-act="nav"][data-v="hoje"]');return t.S().songs.length===nSongs&&!t.S().days['2020-01-01'];`);
  await test('perfis: criar um segundo perfil', `const t=__t;t.perfil();document.querySelector('#prof-name').value='Teste';setTimeout(()=>t.click('[data-act="prof-add"]'),50);return true;`);
  await reloaded; await browser.eval(HELPERS);
  await test('segundo perfil abre do zero; o principal continua salvo', `const t=__t;const reg=JSON.parse(localStorage.getItem('violao-diario-perfis'));const fresh=!!document.querySelector('[data-act="ob-go"]');const main=JSON.parse(localStorage.getItem('violao-diario-v1'));reg.current='';localStorage.setItem('violao-diario-perfis',JSON.stringify(reg));return reg.list.length===1&&fresh&&main&&main.onboarded===true;`);
  await browser.goto(srv.url); await browser.eval(HELPERS);
  await test('de volta ao principal, com o progresso e sem erros registrados', `const t=__t;return t.S().onboarded===true&&t.view()==='hoje'&&t.errs().length===0;`);

  // Microfone sintético: osciladores no lugar do microfone, um por nota; cada getUserMedia recebe um stream novo
  // (o app encerra as faixas ao desligar o microfone).
  await browser.eval(`window.__mic={ctx:null,oscs:{},setup(){if(!this.ctx){this.ctx=new AudioContext();navigator.mediaDevices.getUserMedia=async()=>{const d=this.ctx.createMediaStreamDestination();this.dest=d;Object.values(this.oscs).forEach(x=>x.g.connect(d));return d.stream;};}return this;},
    note(m,on){this.setup();if(on&&!this.oscs[m]){const o=this.ctx.createOscillator();o.frequency.value=440*Math.pow(2,(m-69)/12);const g=this.ctx.createGain();g.gain.value=.15;o.connect(g);if(this.dest)g.connect(this.dest);o.start();this.oscs[m]={o,g};}else if(!on&&this.oscs[m]){this.oscs[m].o.stop();delete this.oscs[m];}},
    chord(ms){Object.keys(this.oscs).forEach(m=>this.note(+m,false));ms.forEach(m=>this.note(m,true));}};'ok'`);
  await test('microfone: contar trocas pelo som (G e C)', `const t=__t,m=__mic.setup();t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="trocas"]');
    for(const [id,v] of [['t-a','G'],['t-b','C']]){const s=document.querySelector('#'+id);s.value=v;s.dispatchEvent(new Event('change',{bubbles:true}));}
    t.click('[data-act="t-mode"][data-v="mic"]');const real=Date.now;let off=0;Date.now=()=>real()+off;
    m.chord([43,47,50,55,59,67]);t.click('[data-act="t-start"]');await t.wait(500);off+=3000;await t.wait(700);
    for(let i=0;i<4;i++){m.chord(i%2?[43,47,50,55,59,67]:[48,52,55,60,64]);await t.wait(700);}
    const count=+document.querySelector('#t-n').textContent;off+=61000;await t.wait(500);Date.now=real;m.chord([]);
    const rec=t.S().changes['C|G'];if(!(count>=3&&rec&&rec.length===1&&rec[0].n===count))throw new Error('contou '+count+', registro '+JSON.stringify(rec));return count;`);
  await test('microfone: conferir o acorde pelo som (Am)', `const t=__t,m=__mic.setup();m.chord([45,52,57,60,64]);t.click('[data-act="nav"][data-v="acordes"]');t.click('[data-act="sub"][data-g="acordes"][data-v="acordes"]');t.click('[data-act="sub"][data-g="filtro"][data-v="todos"]');
    [...document.querySelectorAll('[data-act="chk-open"]')].find(x=>x.dataset.c==='Am').dispatchEvent(new MouseEvent('click',{bubbles:true}));await t.wait(1500);const ok=document.querySelector('#chk-msg').textContent;
    m.note(60,false);await t.wait(1500);const miss=document.querySelector('#chk-msg').textContent;t.click('[data-act="chk-close"]');m.chord([]);
    if(!/Soou como Am/.test(ok)||!/2ª corda/.test(miss))throw new Error(ok+' | '+miss);return true;`);
  await test('microfone: cantar a nota', `const t=__t,m=__mic.setup();t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="ouvido"]');t.click('[data-act="sub"][data-g="ouvido"][data-v="sing"]');
    t.click('[data-act="sing-mic"]');await t.wait(500);let hit=false;for(const p of [52,53,55,57,59,60,62]){m.chord([p]);await t.wait(900);if(/Certo/.test(document.querySelector('#sing-msg').textContent)){hit=true;break;}}
    t.click('[data-act="sing-mic"]');m.chord([]);if(!hit)throw new Error('nenhuma nota reconhecida como certa');return t.S().ear.ok>=1;`);
  await test('afinador: Lá de referência em 442 Hz muda a leitura do microfone', `const t=__t,m=__mic.setup();t.click('[data-act="nav"][data-v="ferramentas"]');t.click('[data-act="sub"][data-g="ferramentas"][data-v="afinador"]');t.click('[data-act="tune-mode"][data-v="crom"]');t.click('[data-act="mic"]');await t.wait(400);
    const o=m.ctx.createOscillator();o.frequency.value=442;const g=m.ctx.createGain();g.gain.value=.2;o.connect(g);g.connect(m.dest);o.start();
    const cents=()=>{const x=/-?\\d+/.exec(document.querySelector('#t-cents').textContent);return x?+x[0]:null;};
    await t.wait(900);const c440=cents(),n440=document.querySelector('#t-note').textContent;t.click('[data-act="a4"][data-v="442"]');await t.wait(900);const c442=cents();o.stop();t.click('[data-act="a4"][data-v="440"]');t.click('[data-act="tune-mode"][data-v="cordas"]');t.click('[data-act="mic"]');
    if(t.S().a4!==440)throw new Error('a4 '+t.S().a4);if(c440==null||c442==null)throw new Error('sem leitura: '+c440+' '+c442+' ('+n440+')');if(Math.abs(c440-8)>3||Math.abs(c442)>3)throw new Error('cents com 440: '+c440+', com 442: '+c442);return /^(A|Lá)/.test(n440);`);
  await test('evolução: trocas por minuto por semana e ouvido por modalidade', `const t=__t;t.click('[data-act="nav"][data-v="treinar"]');t.click('[data-act="sub"][data-g="treinar"][data-v="ouvido"]');t.click('[data-act="sub"][data-g="ouvido"][data-v="mm"]');if(!document.querySelector('[data-act="ear-ans"]'))t.click('[data-act="ear-play"]');const a=document.querySelector('[data-act="ear-ans"]');if(!a)throw new Error('sem pergunta de ouvido');t.click('[data-act="ear-ans"][data-v="'+a.dataset.v+'"]');
    t.click('[data-act="nav"][data-v="evolucao"]');t.click('[data-act="sub"][data-g="evolucao"][data-v="numeros"]');const txt=t.text();if(!/Ouvido por modalidade/.test(txt)||!/Maior ou menor/.test(txt))throw new Error('sem o ouvido por modalidade');if(Object.keys(t.S().changes).length&&!document.querySelector('svg[aria-label^="Melhor troca por minuto"]'))throw new Error('sem o gráfico das trocas');return true;`);
  await test('afinação guiada: cada corda afinada ganha o ✓ na lista', `const t=__t,m=__mic.setup();t.click('[data-act="nav"][data-v="ferramentas"]');t.click('[data-act="sub"][data-g="ferramentas"][data-v="afinador"]');t.click('[data-act="tune-mode"][data-v="cordas"]');t.click('[data-act="mic"]');await t.wait(400);if(!document.querySelector('#tune-guide'))throw new Error('sem a lista guiada');
    m.chord([40]);await t.wait(1500);const e6=document.querySelector('#tune-guide li[data-si="0"]').classList.contains('ok');m.chord([45]);await t.wait(1500);const a5=document.querySelector('#tune-guide li[data-si="1"]').classList.contains('ok');m.chord([]);t.click('[data-act="mic"]');if(!e6||!a5)throw new Error('6ª '+e6+', 5ª '+a5);return true;`);
  await test('gravação de 30 segundos (gravar, guardar, listar)', `const t=__t,m=__mic.setup();m.chord([57]);t.click('[data-act="nav"][data-v="hoje"]');const d=document.querySelector('#hoje-more');if(d)d.open=true;
    if(!document.querySelector('[data-act="rec-start"]'))return 'sem MediaRecorder';t.click('[data-act="rec-start"]');await t.wait(2600);t.click('[data-act="rec-stop"]');await t.wait(900);m.chord([]);
    const recs=t.S().recs;if(recs.length!==1||recs[0].sec<2)throw new Error('gravações: '+JSON.stringify(recs));t.click('[data-act="open-recs"]');await t.wait(150);return !!document.querySelector('#rec-audio')&&document.querySelectorAll('[data-act="rec-play"]').length===1;`);
  await test('acessibilidade: nomes, rótulos, descrições e contraste', `const t=__t,bad=[];
    const chk=tag=>{document.querySelectorAll('#view button,#tabs button').forEach(b=>{if(!(b.textContent.trim()||b.getAttribute('aria-label')||b.title))bad.push(tag+': botão sem nome ('+(b.dataset.act||b.className)+')');});
      document.querySelectorAll('#view input,#view select,#view textarea').forEach(i=>{if(!(i.getAttribute('aria-label')||(i.id&&document.querySelector('label[for="'+i.id+'"]'))))bad.push(tag+': campo sem rótulo ('+(i.id||i.className)+')');});
      document.querySelectorAll('#view svg').forEach(s=>{if(!(s.getAttribute('aria-label')||s.getAttribute('aria-hidden')==='true'||s.closest('[aria-label]')||s.closest('button')))bad.push(tag+': desenho sem descrição');});
      document.querySelectorAll('#view img').forEach(i=>{if(!i.hasAttribute('alt'))bad.push(tag+': imagem sem alt');});};
    for(const [v,subs] of [['hoje',[]],['meu',[]],['treinar',['trocas','batidas','tempo','ouvido']],['ferramentas',['metronomo','afinador']],['acordes',['acordes','notas','teoria','descobrir']],['evolucao',['numeros','roteiro','musicas']]]){t.click('[data-act="nav"][data-v="'+v+'"]');chk(v);for(const s of subs){t.click('[data-act="sub"][data-v="'+s+'"]');chk(v+'/'+s);}}
    t.perfil();chk('perfil');
    const lum=c=>{const k=c.match(/\\d+/g).map(Number),f=x=>{x/=255;return x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4);};return .2126*f(k[0])+.7152*f(k[1])+.0722*f(k[2]);},ratio=(a,b)=>{const [x,y]=[lum(a),lum(b)].sort((p,q)=>q-p);return (x+.05)/(y+.05);};
    const probe=document.createElement('div');document.body.appendChild(probe);const col=v=>{probe.style.color='var('+v+')';return getComputedStyle(probe).color;};
    for(const theme of ['light','dark']){document.documentElement.dataset.theme=theme;[['--ink','--bg'],['--ink','--surface'],['--muted','--surface'],['--muted','--bg'],['--on-primary','--primary'],['--primary','--surface']].forEach(([f,b])=>{const r=ratio(col(f),col(b));if(r<4.5)bad.push('contraste '+theme+': '+f+' sobre '+b+' = '+r.toFixed(2));});}
    delete document.documentElement.dataset.theme;probe.remove();t.click('[data-act="nav"][data-v="hoje"]');
    if(bad.length)throw new Error([...new Set(bad)].slice(0,12).join('; '));return true;`);
  // auditoria de acessibilidade (axe-core, devDependency) em cada tela: falha em problemas sérios ou críticos das regras WCAG A e AA
  let AXE = '';try { AXE = readFileSync(new URL('../node_modules/axe-core/axe.min.js', import.meta.url), 'utf8'); } catch (e) { console.log('axe-core não instalado (npm ci): auditoria de acessibilidade pulada.'); }
  if (AXE) {
    await browser.eval(AXE + ';"ok"');
    await test('acessibilidade: auditoria axe-core sem problemas sérios ou críticos em todas as telas', `const t=__t,bad=[];const run=async tag=>{const r=await axe.run({exclude:[['#toast']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa']},resultTypes:['violations']});r.violations.filter(v=>v.impact==='serious'||v.impact==='critical').forEach(v=>bad.push(tag+': '+v.id+' ('+v.nodes.length+'x, '+v.nodes[0].target.join(' ')+')'));};
      for(const [v,subs] of [['hoje',[]],['meu',[]],['treinar',['trocas','batidas','tempo','ouvido']],['ferramentas',['metronomo','afinador']],['acordes',['acordes','notas','teoria','descobrir']],['evolucao',['numeros','roteiro','musicas']]]){t.click('[data-act="nav"][data-v="'+v+'"]');await run(v);for(const s of subs){t.click('[data-act="sub"][data-v="'+s+'"]');await run(v+'/'+s);}}
      t.perfil();await run('perfil');t.click('[data-act="nav"][data-v="hoje"]');if(bad.length)throw new Error(bad.slice(0,8).join('; '));return true;`);
  }
} finally {
  await browser.close(); srv.close();
}
console.log(`Testes de tela: ${results.length - failed} de ${results.length} passaram.`);
if (failed) process.exit(1);
